/// Flutter icons Leaderboard
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Leaderboard
///      fonts:
///       - asset: fonts/Leaderboard.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Leaderboard {
  Leaderboard._();

  static const _kFontFam = 'Leaderboard';
  static const _kFontPkg = null;

  static const IconData leaderboard_24px = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
